[package]
name = "cognitive-services-speech-sdk-rs"
version = "0.1.0"
authors = ["Adam Bezecny <adam.bezecny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8.3"
tokio = {version = "1.2.0", features = ["full"]} 

[build-dependencies]
bindgen = "0.57.0"